company:
  email: "infor@framgia.com"
image:
  size:
    logo: "33x21"
    avatar: "80x80"
    category: "360x224"
    food_show: "300x200"
    food_size: "750x223"
    food_edit: "100x100"
    food_index: "200x100"
    header_search: "25x22"
    header_avatar: "25x22"
    product_order: "80x80"
    out_stock: "160x40"
    favorite_food: "140x140"
paginate:
  per_page: 3
  users_per_page: 10
  quantity_per_page: 5
avatar:
  size: 80
gravatar_user:
  size: 50
cookies:
  time:
    orders: 1
user:
  maxname: 10
